name: repro-workflow
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - pandas==2.2.*
      - numpy==1.26.*
      - matplotlib==3.8.*
      - scipy==1.13.*
      - pyarrow==15.*
      - jupyterlab==4.2.*
      - nbformat==5.10.*
      - papermill==2.6.*
